### ISSUE TITLE
WP1903 has a complex with an ChEBI identifiers which is not an ChEBI identifier

### ISSUE THREAD

**Issue by egonw** [wikipathways/reactome2gpml-converter#46]
The output GPML on WikiPathways is (r83141):

```
  <DataNode TextLabel="DAG" GraphId="e667d" Type="Complex">
    <Attribute Key="cellular_location" Value="plasma membrane" />
    <Graphics CenterX="491.5" CenterY="29.0" Width="35.0" Height="22.0" ZOrder="32768" FontSize="10" Valign="Middle" ShapeType="RoundedRectangle" Color="a52a2a" />
    <Xref Database="ChEBI" ID="R-HSA-CHEBI:17815" />
  </DataNode>
```

However, "R-HSA-CHEBI:17815" is not a ChEBI identifier. I am not sure how to check the Reactome source and not sure if the problem is in the convertor code or in the Reactome pathway source.

**Comment by egonw** [comment]
I just had another look at this... there is a Complex and a Metabolite... what about collapsing complexes with only one participant into just that participant? So, for WP1903 do not have a DAG Complex in the main pathway, but just the Metabolite DAG?

**Comment by DeniseSl22** [comment]
I'll check this PW out when we have the 62 version up and running! But good idea to change complexes with only one datanode in them to general datanodes.

**Comment by egonw** [comment]
This problem is fixed.
