### ISSUE TITLE
create a working build.xml (Ant) or pom.xml (Maven) to compile the software

### ISSUE THREAD

**Issue by egonw** [wikipathways/reactome2gpml-converter#53]
Which is needed for CI on our Jenkins server.

**Comment by egonw** [comment]
See also https://github.com/wikipathways/reactome2gpml-converter/issues/45

**Comment by DeniseSl22** [comment]
Yes, I'll work on this when I have time.... I think I could work out the ant build myself; don't have experience with the Maven build, so perhaps we can check that later together :)

**Comment by egonw** [comment]
yes, that's why I assigned it to both of us... Friday?

**Comment by DeniseSl22** [comment]
I thought you were going through your applicants on Friday first ;) This isn't a priority for this week right? Next week is also fine I believe :)

**Comment by DeniseSl22** [comment]
Tina create a working ant file (commit e1b2d71).... do we still need the pom one then too? Because the MySQL database is quite large, I don't know if you want to run all this on the Jenkins server....

**Comment by DeniseSl22** [comment]
The converter is still not being built in jenkins automatically; even though the new build.xml file is in the workspace.... Need to dive into this in more detail later.

**Comment by egonw** [comment]
It is now: https://jenkins.bigcat.unimaas.nl/job/reactome2gpml-converter/
