### ISSUE TITLE
Add Luc to this repo + Run MySQL on server

### ISSUE THREAD

**Issue by DeniseSl22** [wikipathways/reactome2gpml-converter#74]
@mkutmon @egonw  I'm not sure who has access to do so (not me at least), but could one of you please add Luc to this repo?
So he can check what I need to make this stuff work on a server :)

**Comment by egonw** [comment]
Done. @DeniseSl22, plz make sure he accepts the invitation (in time).

**Comment by DeniseSl22** [comment]
He's already accepted the invite :)

@LucDM, could you please set up something on the server so I can run the .jar from this repo on an MySQL-database? :)

**Comment by LucDM** [comment]
Hi, all... reading up... OK Denise, you need command-line access to run the jar as specified on a to-be-created mysql database I think I understand. Is this what you wanted to run on the calculations-server as we discussed a while ago? (meaning, the conversion is a heavy job, needs be done quickly and repeatedly, large database?

**Comment by LucDM** [comment]
Which database from https://reactome.org/download-data ??? Or get the MySQL dump of all databases and thus replicate the reactome database?

**Comment by DeniseSl22** [comment]
> Hi, all... reading up... OK Denise, you need command-line access to run the jar as specified on a to-be-created mysql database I think I understand.

Yes, correct!

> Is this what you wanted to run on the calculations-server as we discussed a while ago? (meaning, the conversion is a heavy job, needs be done quickly and repeatedly?

No, that's for another project (Still waiting for Tina to give you access to that repo, involving Neo4j calculations). But running this project with MySQL also takes quite some calculation time (normally 4 hours or so, with 16 GB, if I remember correctly).

> And I need to download Reactome database and create the mysql database with that... I think..

Yes, there should be an option on their website to download the MySQL database. See image below:
![image](https://user-images.githubusercontent.com/26277832/90642124-4a3d6080-e232-11ea-91e9-22d9f3e74faf.png)

There is also a place to download previous versions; I have that somewhere in my mail (will look it up).

> Which database from https://reactome.org/download-data ??? Or get the MySQL dump of all databases and thus replicate all the reactome databases locally?
> 
> Sort of right?

Everything from version 66 (they're now up to 73).

**Comment by DeniseSl22** [comment]
@LucDM : I've found the email where they explain where their archived data is:
```
To get the version 62, 63, and 64 Reactome MySQL databases, you can download our archives for those versions here:
 
https://reactome.org/download/archive/64.tgz
https://reactome.org/download/archive/63.tgz
https://reactome.org/download/archive/62.tgz
 
The MySQL dump of the Reactome database can be found in the tar file under XX/databases/gk_current.sql.gz where XX is the Reactome version.
 
One thing to note is these archive files are quite large, so please let us know if you have any trouble downloading or extracting what you need.
```

however, the links don't work anymore... I'll ask the Reactome team what the current one is :)

**Comment by DeniseSl22** [comment]
@LucDM @egonw @mkutmon : I've discussed the Reactome updates with Tina, and she believes that to finish the DSMN paper, we would only need to convert the latest Reactome MySQL database, and use the GPML to RDF code which Egon can run locally. When I have the RDF of the latest Reactome, I can add it to Blazegraph and query it. Please let me know when you (Luc and Egon) have time to help me with this.

**Comment by egonw** [comment]
Okay, not sure what to do with this. What skills are you missing? What tasks need to be done but you do not know how?

**Comment by LucDM** [comment]
I know too little of gpml and rdf to help doing that at this time... sorry.

**Comment by egonw** [comment]
so, in the future, it should be like this:

1. fire up a DSRi with a Docker with MySQL
2. automatically load the latest Reactome SQL
3. fire up another service to generate the GPML
4. fire up another service to generate the RDF

**Comment by DeniseSl22** [comment]
Yes, these four steps are needed indeed. What I would need Luc for, is step 1 +2. I can run the converter to obtain the GPMLs.
If I'm correct, @egonw set up the 4th step locally; so if it's not too much work I can do that as well (where is the documentation for that)?

**Comment by LucDM** [comment]
That I CAN do if you can write out the sequence and conversion programs to be used to accomplish this. Explain to me how I would need to do this manually or show it to me using screen-sharing.

**Comment by LucDM** [comment]
if you need a bridge file than I can send it via wetransfer.  @mkutmon I didn't think about wetransfer when I sent the email out yesterday...

**Comment by DeniseSl22** [comment]
@LucDM : I have never executed step 1+2 myself, this was always done by Nuno; so I cannot show you the steps unfortunately (nor do I know if there is documentation on it). Hoping @mkutmon and/or @egonw know more about this :)

**Comment by egonw** [comment]
Yeah, should not be hard. This is also how I created the first ChEMBL RDF many moons ago but I just don't have the time right now :(

**Comment by LucDM** [comment]
The database load is not the problem for me I think. The last 2 steps I need explained.

**Comment by DeniseSl22** [comment]
Now running the converter as Docker, thanks to Ammar. Will close this issue for now.
